# deploy-site.yml
- name: Deploy Static Website to AWS S3
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # These variables will be passed in from the GitHub Actions workflow
    s3_bucket_name: "{{ lookup('env', 'S3_BUCKET_NAME') }}"
    build_directory: "{{ lookup('env', 'BUILD_DIRECTORY') }}"

  tasks:
    - name: Ensure required variables are set
      ansible.builtin.assert:
        that:
          - s3_bucket_name is defined and s3_bucket_name!= ''
          - build_directory is defined and build_directory!= ''
        fail_msg: "S3_BUCKET_NAME and BUILD_DIRECTORY environment variables must be set."

    - name: Synchronize static site files with S3 bucket
      community.aws.s3_sync:
        bucket: "{{ s3_bucket_name }}"
        file_root: "{{ build_directory }}"
        mode: push
        # 'checksum' is more accurate than 'date_size' as it compares file content hashes.
        file_change_strategy: checksum
        # Exclude hidden files (like.DS_Store) from the upload.
        exclude: ".*"
      register: sync_results

    - name: Display sync summary
      ansible.builtin.debug:
        msg: "Successfully uploaded {{ sync_results.uploaded | length }} new/modified files to S3 bucket {{ s3_bucket_name }}."
